services:
  bot:
    image: discord-music-bot:debug
    build:
      context: .
    command: ["sh", "-c", "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 bot.py "]
    ports:
      - 5678:5678
    volumes: 
      - music:/usr/src/app/music
    environment:
      # Values assigned here will override env_file contents.
      DISCORD_PREFIX:
      DISCORD_TOKEN:
    env_file: .env

volumes:
  music:
